services:
  tomcat-file-server:
    image: tomcat:8.5.23-alpine
    container_name: tomcat-file-server
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./files:/usr/local/tomcat/webapps/ROOT
      - ./config/web.xml:/usr/local/tomcat/conf/web.xml