name: nginx-proxy-manager
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db-nginx
  db-nginx:
    image: yobasystems/alpine-mariadb:latest
    #image: mariadb:latest # original
    restart: always
    environment:
      # do not forget to change any password for productive instance
      MYSQL_ROOT_PASSWORD: 'BVe9ocW2h9F8WFY4Df6A'
      MYSQL_DATABASE: 'nginxproxymanagerDatabase'
      MYSQL_USER: 'nginxproxymanagerUser'
      MYSQL_PASSWORD: 'BVe9ocW2h9F8WFY4Df6A'
    volumes:
      - ./data/mysql:/var/lib/mysql